# AdvancedRobots
# Made by GC
#
# Version: 1.1.5
# Release date: 2019.12.29
#
# ** Commands and permissions
# /ar give <player> [amount] - Give a number of robot spawn eggs;ar.admin
# /ar reload - Reload plugin;ar.admin
# /ar tasks - List robot tasks available;ar.admin
# /ar givetask <player> <task name> [amount] - Give number of specific task to player;ar.admin
#
# Some configurable settings are explained, others should be self-explanatory.
# Contact "GC." on SpigotMC with any questions or bug reports.
#
# Permission to limit robots per player is 'ar.limit.<amount>'
#
# Manage plugin commands
messages:
  cannotPlaceHere:
    - '&cCannot place a robot here!'
  placementOnCooldown:
    - '&cYou must wait &l%timeRemaining%ms &ctill you can place another Robot!'
  noPermission:
    - '&cYou don''t have permission!'
  limitReached:
    - '&cYou cannot place more than %limit% robots!'

# Settings for robots
robots:
  # Default name that robots use upon spawning
  defaultName: '&f&l%playerName%''s &b&lRobot'
  # Robot Managing inventory (Can be opened by right-clicking a robot)
  managingInventory:
    # Should robot managing inventory be enabled
    enabled: true
    name: "&cManage Robot"
    size: 9
    fill:
      fillEmptyItems: true
      material: STAINED_GLASS_PANE
      damage: 15
      name: ' '
      lore: []
    items:
      0:
        material: SKULL_ITEM
        damage: 3
        name: '&aChoose Robot''s Skin'
        lore: []
        # Type sets item behaviour upon player clicking it
        type: 'skinSelector'
      1:
        material: COAL
        damage: 0
        name: '&aAdd Fuel to Robot'
        lore:
          - '&eRemaining time: &6%time%'
          - ''
          - '&7Robots require fuel cells to work.'
          - '&7Click here to start adding fuel to this robot.'
        # Type sets item behaviour upon player clicking it
        type: 'robotFuel'
      4:
        material: ARMOR_STAND
        damage: 0
        name: '&cRobot''s Information'
        lore:
          - '&6&lx &eOwner: &f%owner%'
          - '&6&lx &eTask: &f%task%'
          - '&6&lx &eLocation: &f%x%x %y%y %z%z %world%'

# Configuration for skin selector of robot skulls
skinSelector:
  skins:
    angryRobot:
      name: "Angry Robot"
      # Name of player that uses this skin
      # Supports base64 format to use custom skins (e.g: https://minecraft-heads.com/custom-heads)
      playerSkinName: 'robot'
      # Required permission to put this skin
      permission: ''
    minion:
      name: "Minion"
      playerSkinName: 'minions'
      permission: ''
    miner:
      name: "Miner"
      playerSkinName: 'miner'
      permission: ''
    golden:
      name: "Golden"
      playerSkinName: 'shiny'
      permission: ''
    astronaut:
      name: "Astronaut"
      playerSkinName: 'space'
      permission: ''
  # Skin Selector GUI name
  inventoryName: '&cSkin Selector'
  # Alias used as name to reset robot's skin
  robotsOwnerAlias: 'Robot''s Owner'
  # Should plugin attempt to match skin's dominant color for robot's armor
  matchSkinForArmorColor: true
  # Item used to preview skull in the selector
  skinPreviewItem:
    material: SKULL_ITEM
    damage: 3
    name: '&eClick to choose &6%skinName%'
    lore: []

# Configuration for fuel powered robots
fuel-inventory:
  inventoryName: '&bRobot Fuel'
  confirmedMessage:
    - '&eAdded &lx%amount% &d&lRobot Fuel Cell &7(%time%) &efuel to the robot.'
  confirmItem:
    material: STAINED_GLASS_PANE
    damage: 5
    name: '&aConfirm to add these fuel cells'
    lore:
      - '&eRemaining time: &6%time%'
      - '&7Click to confirm and fuel the robot'

items:
  robot:
    material: MONSTER_EGG
    damage: 101
    name: '&e&lRobot &7[Right-Click to Place]'
    lore: []
  task:
    material: NAME_TAG
    damage: 0
    name: '&e&lRobot Task &f"%taskName%" &7[Right-Click Robot to apply]'
    lore: []
  fuel:
    material: COAL
    glow: true
    damage: 0
    name: '&d&lRobot Fuel Cell &7[Place in Robot]'
    lore:
      - '&7Open a robot and put the fuel in to add'
      - '&b%time% &7to robot''s fuel.'
    settings:
      # How many seconds will 1 fuel cell add to robot?
      seconds-to-add: 600
      # Do robots require fuel cells to work?
      robots-require-fuel: true
