# Name for this task
taskName: 'Miner'
description: 'Mines blocks in-front of it'
handItem: 'IRON_PICKAXE'
# RGB Colors for armor (https://rgbcolorcode.com/)
armorColor: '30,60,66'
robotName: '&f&l%playerName%&r''s &7&lMiner&r'
script:
  # Work types: [MINING, ATTACK, SELL, FISH]
  workType: 'MINING'
  workConfiguration:
    # List of objects to interact with, could be a mob or block materials
    # To add more than one object, use this formatting: 'zombie,skeleton,wither'
    # To allow interaction with all materials, leave this as empty ( '' )
    interactWith: ''
    # damage: <amount> - This setting can be used with 'ATTACK'
    # replant: true - This setting can be used with farming robots
  # How frequent should this task be activated, in seconds
  frequency: 3
  # Interaction configuration
  interaction:
    # If 'ahead' is set to true, robot will only interact with object in-front of robot
    ahead: true
    # If 'ahead' is set to 'false', then radius will be used
    radiusHandler:
      # Radius size, in blocks, to each side. 5 means 5x5x5 (x, y, z) (125) blocks will be affected
      radiusSize: 5
  resourcesTransformation:
    # Should gained resources, such as mined blocks or drops from mobs, be teleported to robot or drop at original location
    teleportToRobot: true
    # Should hopper detection be activated and move drops to a hopper under robot?
    hopperDetection: true
    # Should drops be automtically sold (disables 2 settings above for drops)
    autoSellDrops: false
